import { exportJWK, generateKeyPair, SignJWT, type JWK } from "jose";
import { afterEach, describe, expect, it, vi } from "vitest";
import { isAuthEnabled, verifyAccessJwt } from "../../../src/worker/middleware/auth";

const AUD = "test-application-aud-tag";
const KID = "test-key";

// Each test gets its own team domain so the module-level JWKS cache in auth.ts (keyed by
// domain, meant to avoid re-fetching Access's real public keys on every request) can't leak a
// stale key set generated by an earlier test into a later one.
function uniqueTeamDomain(): string {
  return `https://team-${crypto.randomUUID()}.cloudflareaccess.com`;
}

async function setUpJwks(teamDomain: string): Promise<CryptoKey> {
  const { publicKey, privateKey } = await generateKeyPair("RS256");
  const jwk: JWK = { ...(await exportJWK(publicKey)), kid: KID, alg: "RS256", use: "sig" };

  vi.stubGlobal(
    "fetch",
    vi.fn(async (input: RequestInfo | URL) => {
      const url = input instanceof Request ? input.url : String(input);
      if (url === `${teamDomain}/cdn-cgi/access/certs`) {
        return new Response(JSON.stringify({ keys: [jwk] }), {
          headers: { "content-type": "application/json" },
        });
      }
      throw new Error(`unexpected fetch: ${url}`);
    }),
  );

  return privateKey;
}

function signToken(
  privateKey: CryptoKey,
  options: { issuer: string; audience?: string; expiresIn?: string; claims?: Record<string, unknown> },
) {
  return new SignJWT({ email: "edd@example.com", name: "Edd", ...options.claims })
    .setProtectedHeader({ alg: "RS256", kid: KID })
    .setIssuer(options.issuer)
    .setAudience(options.audience ?? AUD)
    .setIssuedAt()
    .setExpirationTime(options.expiresIn ?? "5m")
    .sign(privateKey);
}

describe("verifyAccessJwt", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("returns undefined when ACCESS_TEAM_DOMAIN and/or ACCESS_AUD aren't configured", async () => {
    await expect(verifyAccessJwt("whatever", {})).resolves.toBeUndefined();
    await expect(
      verifyAccessJwt("whatever", { ACCESS_TEAM_DOMAIN: uniqueTeamDomain() }),
    ).resolves.toBeUndefined();
    await expect(verifyAccessJwt("whatever", { ACCESS_AUD: AUD })).resolves.toBeUndefined();
  });

  it("resolves the identity for a validly signed token", async () => {
    const teamDomain = uniqueTeamDomain();
    const privateKey = await setUpJwks(teamDomain);
    const token = await signToken(privateKey, { issuer: teamDomain });

    await expect(
      verifyAccessJwt(token, { ACCESS_TEAM_DOMAIN: teamDomain, ACCESS_AUD: AUD }),
    ).resolves.toEqual({ email: "edd@example.com", name: "Edd" });
  });

  it("rejects a token signed for a different Access application (wrong audience)", async () => {
    const teamDomain = uniqueTeamDomain();
    const privateKey = await setUpJwks(teamDomain);
    const token = await signToken(privateKey, { issuer: teamDomain, audience: "some-other-app-aud" });

    await expect(
      verifyAccessJwt(token, { ACCESS_TEAM_DOMAIN: teamDomain, ACCESS_AUD: AUD }),
    ).resolves.toBeUndefined();
  });

  it("rejects an expired token", async () => {
    const teamDomain = uniqueTeamDomain();
    const privateKey = await setUpJwks(teamDomain);
    const token = await signToken(privateKey, { issuer: teamDomain, expiresIn: "-1s" });

    await expect(
      verifyAccessJwt(token, { ACCESS_TEAM_DOMAIN: teamDomain, ACCESS_AUD: AUD }),
    ).resolves.toBeUndefined();
  });

  it("rejects a token issued by a different team domain", async () => {
    const teamDomain = uniqueTeamDomain();
    const privateKey = await setUpJwks(teamDomain);
    const token = await signToken(privateKey, { issuer: "https://a-different-team.cloudflareaccess.com" });

    await expect(
      verifyAccessJwt(token, { ACCESS_TEAM_DOMAIN: teamDomain, ACCESS_AUD: AUD }),
    ).resolves.toBeUndefined();
  });

  it("rejects a validly signed token with no email claim", async () => {
    const teamDomain = uniqueTeamDomain();
    const privateKey = await setUpJwks(teamDomain);
    const token = await signToken(privateKey, { issuer: teamDomain, claims: { email: undefined } });

    await expect(
      verifyAccessJwt(token, { ACCESS_TEAM_DOMAIN: teamDomain, ACCESS_AUD: AUD }),
    ).resolves.toBeUndefined();
  });

  it("rejects a garbage token", async () => {
    const teamDomain = uniqueTeamDomain();
    await setUpJwks(teamDomain);

    await expect(
      verifyAccessJwt("not-a-jwt", { ACCESS_TEAM_DOMAIN: teamDomain, ACCESS_AUD: AUD }),
    ).resolves.toBeUndefined();
  });
});

describe("isAuthEnabled", () => {
  const DB = {} as D1Database;

  it("is enabled on a real deployment, where the bypass var is unset", () => {
    expect(isAuthEnabled({ DB })).toBe(true);
  });

  it("is disabled wherever the dev bypass is on (standalone Docker, wrangler dev)", () => {
    expect(isAuthEnabled({ DB, DEV_AUTH_BYPASS_ENABLED: "true" })).toBe(false);
  });

  it("treats any value other than the exact string \"true\" as auth still being on", () => {
    expect(isAuthEnabled({ DB, DEV_AUTH_BYPASS_ENABLED: "false" })).toBe(true);
    expect(isAuthEnabled({ DB, DEV_AUTH_BYPASS_ENABLED: "1" })).toBe(true);
    expect(isAuthEnabled({ DB, DEV_AUTH_BYPASS_ENABLED: "TRUE" })).toBe(true);
  });
});
